@startditaa

+----+
| IV +---------------------------------------IV-------------+
+----+                                                      |
                                                    +-------+-------+            +----------------+
+---------------+    +----------------+             |               |            | Authentication |
| user password +--->|   SHA256 hash  +------key----+ AES enryption |---cipher---+   Challenge    |
+---------------+    |  (32bit long)  |             |               |            |    Response    |
                     +----------------+             +-------+-------+            +----------------+
                                                            |
+---------------------------------+                         | 
| Authentication Challenge String +----------plain----------+
+---------------------------------+
                     
@endditaa
