@startditaa

+------------+
| session id +---------------------------IV-----------------+
+------------+                                              |
                                                    +-------+-------+            +----------------+
+---------------+    +----------------+             |               |            | Authentication |
| user password +--->|   SHA256 hash  +------key----+ AES enryption |---cipher---+   Challenge    |
+---------------+    |  (32byte long) |             |               |            |    Response    |
                     +----------------+             +-------+-------+            +----------------+
                                                            |
+---------------------------------+                         | 
| Authentication Challenge String +----------plain----------+
+---------------------------------+
                     
@endditaa
