@startuml

' configuration
hide circle
skinparam linetype ortho

' comment

entity "APPLICATIONS" as app {
APP_ID : int
--
APP_NAME : string
APP_DATA_PUBLISHER : string
}

entity "SYSTEM_PARAMS" as sysParam {
PARAM_NAME : string
--
PARAM_VALUE : string
}

entity "APPLICATION_PARAMS" as appParam {
APPLICATION_ID : int
NAME : string
--
PUBLIC : int
VALUE : string
}

entity "USER_SETTINGS" as userParams {
APPLICATION_ID : int
APPLICATION_PARAM_NAME : string
USER_ID : string
--
VALUE : string
}

entity "ROLES" as userRoles {
NAME : string
--
DESCRIPTION : string
}

entity "USERS" as user {
USER_ID : string
--
FIRST_NAME : string 
LAST_NAME : string
PASS_HASH : string 
}


entity "PRIVILEGES" as rolePrivileges {
SHORT_DESC : string
--
LONG_DESC : string
}

entity "ROLE2PRIVILEGE" as r2p {
ROLE_NAME : string
PRIVILEGE_SHORT_DESC : string  
}

entity "USER2ROLE" as u2p {
USER_ID : string
ROLE_NAME : string
}


userParams }o--|| app
userParams  }o--|| user
appParam }o--|| app
userParams |o--|| appParam 
user }o--|| u2p
userRoles }o--|| u2p
userRoles }o--|| r2p
rolePrivileges }o--|| r2p
@enduml